services:
  sylius-php:
    build:
      context: .
      dockerfile: ./docker/local/php/Dockerfile
    container_name: sylius_php
    volumes:
      - ./:/var/www/html       # Mount Sylius project directory
      - ./docker/local/php/php.ini:/usr/local/etc/php/php.ini  # Mount custom php.ini
    working_dir: /var/www/html
    depends_on:
      - sylius-mariadb
  sylius-mariadb:
    image: mariadb:10.5
    ports:
      - "3306:3306"
    container_name: sylius_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
  sylius-nginx:
    image: nginx:latest
    container_name: sylius-nginx
    volumes:
      - ./docker/local/nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # Mount Nginx config
      - ./:/var/www/html       # Mount Sulu project directory
    ports:
      - "80:80"
    depends_on:
      - sylius-php

volumes:
  db_data: